Repository retaildevcrews/helium-terraform, pull requests merged in 2020-09, with the labels that each got.

#37 issue #36 - Updated terraform to fix Access Policy
  src/modules/webapp/main_kv.tf
Labels: Terraform, size: S

#44 Start of AKS deployment for terraform. Documentation and initial resource group.
  .gitignore
  src/aks/README.md
  src/aks/main.tf
  src/aks/variables.tf
Labels: Documentation, Terraform, customer feedback

#38 Updated storage account name in create-tf-vars.sh
  src/root/create-tf-vars.sh
Labels: Terraform

#42 Added link checks for .md files to CI
  .github/ISSUE_TEMPLATE/user_story.md
  .github/workflows/mdlinkcheck.yml
  mlc_config.json
Labels: Bug, Documentation, Pri1, Terraform

#45 Fix Creating terraform.tfvars Inconsistencies
  src/example.tfvars
  src/root/create-tf-vars.sh
Labels: Bug, Terraform

#49 temporarily disable ci-cd
  .github/workflows/tfvalid.tmp
Labels: Terraform

#48 Creating public aks cluster
  src/aks/main.tf
Labels: Terraform

#50 Creating AKS Pod Identity + using locals
  src/aks/main.tf
Labels: Terraform

#51 Added scheduled checks to CI
  .github/ISSUE_TEMPLATE/found-dead-links.md
  .github/workflows/mdlinkcheck.yml
  .github/workflows/scheduled_mdlinkcheck.yml
Labels: Bug, Documentation

#52 Role assignments for AKS MIs
  src/aks/README.md
  src/aks/main.tf
Labels: Terraform

#53 Updated scheduled link check to create project cards
  .github/workflows/scheduled_mdlinkcheck.yml
Labels: Bug, CI/CD, Documentation
