Repository retaildevcrews/helium-terraform, pull requests merged in 2020-08, with the labels that each got.

#28 Add Cosmos DB Throttle Alerts
  src/modules/db/main_alerts.tf
  src/modules/db/variables.tf
  src/root/main.tf
Labels: Pri1, Terraform, good-first-issue, size: S

#29 Update the webv instances created by terraform to use latest image
  src/modules/aci/main.tf
Labels: Bug, Terraform, size: S

#30 Fix sed errors in create-tf-vars.sh on macOS
  src/root/create-tf-vars.sh
Labels: Bug, Terraform

#32 Updated create_tfvars.sh to store tfstate remotely
  .devcontainer/post-install.sh
  .gitignore
  src/modules/webapp/main_state.tf
  src/root/create-tf-vars.sh
  src/root/main.tf
Labels: Bug, Pri2, Terraform

#33 Updating GH templates, master to main changes
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/checkpoint.md
  .github/ISSUE_TEMPLATE/comparison.md
  .github/ISSUE_TEMPLATE/designreview.md
  .github/ISSUE_TEMPLATE/dod-review.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/issue.md
  .github/ISSUE_TEMPLATE/release.md
  .github/ISSUE_TEMPLATE/survey.md
  .github/ISSUE_TEMPLATE/task.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/tfvalid.yml
Labels: Terraform

#34 Removed TFSTATE_RG_NAME, updated create-tf-vars.sh
  src/modules/webapp/variables.tf
  src/root/create-tf-vars.sh
  src/root/main.tf
Labels: Bug, Pri2, Terraform

#35 Replace sed with ex in create-tf-vars.sh to for macOS
  src/root/create-tf-vars.sh
Labels: Bug, Terraform
