Repository retaildevcrews/helium-terraform, pull requests merged in 2020-07, with the labels that each got.

#3 Docs updates
  README.md
  todo-list
Labels: terraform

#4 Dockerlogging
  .dockerignore
  CHANGELOG.md
  README.md
  fix
  save
  src/modules/aci/main.tf
  src/modules/acr/main.tf
  src/modules/acr/variables.tf
  src/modules/db/main.tf
  src/modules/db/variables.tf
  src/modules/webapp/main.tf
  src/modules/webapp/main_alerts.tf
  src/modules/webapp/main_backup_tf_state.tf
  src/modules/webapp/main_kv.tf
  src/modules/webapp/variables.tf
  src/root/create-tf-vars.sh
  src/root/main.tf
  src/root/variables.tf
Labels: Pri1

#5 updated readme
  README.md
Labels: terraform

#10 doc bug fix
  README.md
Labels: terraform

#11 Update App Service
  src/modules/aci/main.tf
  src/modules/webapp/main.tf
  src/modules/webapp/main_backup_tf_state.tf
  src/root/create-tf-vars.sh
Labels: terraform

#12 added missing file
  src/modules/webapp/main_state.tf
Labels: terraform

#13 Renaming for review
  src/modules/webapp/main_state.tf
Labels: Bug, size: S, terraform

#14 removed webv app insights
  src/modules/aci/main.tf
  src/modules/webapp/main_state.tf
Labels: terraform

#15 add log analytics
  README.md
  src/example.tfvars
  src/modules/aci/README.md
  src/modules/aci/main.tf
  src/modules/aci/variables.tf
  src/modules/db/main.tf
  src/modules/webapp/main.tf
  src/modules/webapp/main_alerts.tf
  src/modules/webapp/main_dashboard.tf
  src/modules/webapp/main_kv.tf
  src/modules/webapp/main_state.tf
  src/modules/webapp/variables.tf
  src/root/create-tf-vars.sh
  src/root/main.tf
  src/root/variables.tf
  todo-list
Labels: terraform
